### ISSUE TITLE
tm拉取不到binlog

### ISSUE THREAD

**Issue by 1105220927** [ververica/flink-cdc-connectors#1060]
**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version: 2.2.0
 - Database and version: mysql 5.7.30
![image](https://user-images.githubusercontent.com/95424327/162401523-8af30eba-abe0-4cbd-ab75-da06ebb04e1b.png)

我们生产环境使用虚拟ip访问mysql, 这种虚拟ip的机制保证同一个ip同一个账号永远把请求打在同一个从机上，但是不同的ip使用同一个账号可能打在不同的从机上。

目前遇到的问题是，jm通过虚拟ip拿到了从机1的binlog文件，并将对应的任务派发到tm上执行， 而tm上通过虚拟ip的请求打到了从机2上，就会出现上述报错，一直拉不起来。。。

我们目前的场景只进行增量同步，并行度为1， 跪求大佬帮看下这里是不是有没有什么方法解决！！！ （这种虚拟ip的方式应该很多云产品都提供类似的方式，我们目前使用的是腾讯云）

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
