### ISSUE TITLE
增量数据同步，出现访问IO问题

### ISSUE THREAD

**Issue by PengMinghui973** [ververica/flink-cdc-connectors#1095]
![image](https://user-images.githubusercontent.com/62225711/164227182-c8901605-4553-49c0-b838-40be63b83972.png)
什么情况同步数据会出现这种情况，方便解答下吗，谢谢

**Comment by GOODBOY008** [comment]
It's occurs after snapshot process completed?

**Comment by PengMinghui973** [comment]
> 它是在快照过程完成后发生的吗？

是的，全量同步完后，增量同步报错这个io，如果是网络超时，是否可以在哪设置超时时间解决在这个问题，目前同步数量量少的表没出现这种情况

**Comment by PengMinghui973** [comment]
> > 
> 
> 能不能用branch master来打包测试？Branch master 已将 debezium 版本升级到 1.6.4。

我使用flink cdc 2.0.1 已经最新的2.2.1都会报错这个问题

**Comment by PengMinghui973** [comment]
> > 
> 
> 能不能用branch master来打包测试？分支大师已将 debezium 版本升级到 1.6.4。

版本升级解决不了这个问题，是不是还有其它设置可以解决这个bug?

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
