### ISSUE TITLE
How to monitor if the connector's progress is behind MySQL binlog ?

### ISSUE THREAD

**Issue by xiaolong-sn** [ververica/flink-cdc-connectors#118]
Hi,

We are trying to sync from MySql to HBase. Everything is fine but I wonder how to monitor if the connector is way behind binlog. 

I recall that when I used to setup a Canal service, we can collect how much late the service is since Canal acts as a slave instance for MySQL. How can we monitor the lateness of our job comparing to MySql binlog ?

Thanks !

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
