### ISSUE TITLE
Add pom guide for datastream users who use the different flink version

### ISSUE THREAD

**Issue by fsk119** [ververica/flink-cdc-connectors#1187]
Datastream users need shade guava by themselves. I think we should offer these examples for them.

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
