### ISSUE TITLE
java.lang.AbstractMethodError: Method org/apache/kafka/connect/json/JsonSerializer.configure(Ljava/util/Map;Z)V is abstract

### ISSUE THREAD

**Issue by ruanzy** [ververica/flink-cdc-connectors#122]

**Comment by NobleYd** [comment]
我看了下maven包中shade了很多其他包进去，但是没用relocation，其中kakfa这种flink中很常用的包，很容易和业务自己引入的kafka冲突。不清楚作者是否考虑调整下呢？

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
