### ISSUE TITLE
Oracle supports xStream

### ISSUE THREAD

**Issue by luobo-te** [ververica/flink-cdc-connectors#1221]
does oracle-cdc support xStream?  Debezium already supports
oracle-cdc支持oracle xstream采集吗 ？底层debezinum是支持的

**Comment by hehetown** [comment]
Oracle-cdc supports Oracle XStream,You could write it like this: 'debezium.database.connection.adapter' = 'xstream',
    'debezium.database.out.server.name' = 'DBZXOUT_DEMO',

**Comment by gong** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you! 
cc @GOODBOY008

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
