### ISSUE TITLE
[Feature] Postgres 高可用模式下 Connector 启动和断线重连

### ISSUE THREAD

**Issue by ianhhhhhhhhe** [ververica/flink-cdc-connectors#1246]
**Is your feature request related to a problem? Please describe.**
1. 启动的时候 DebeziumSourceFunction 需要连接 PostgreSQL 的 master 节点，所以需要在 task 部署前从地址池里获取 master 地址。这个方法虽然可以通过手动设置，或者在 env.execute() 之前轮询所有地址，并通过 ```select * from pg_stat_replication``` 查询来判断 master，但是第二种情形有不适合。
2. 当 PostgreSQL 的 master 节点出现问题 down 掉了之类的问题造成主从切换，SourceFunction 没有办法自动切换并创建 replication_slot。当前看起来主从切换之后，除了重新 submit 似乎没有其他的方法了。

**Describe the solution you'd like**
所以，希望 PostgreSQL 的 driver 能有种更优雅的方式在构建 SourceFunction 的时候，能主动去地址池里去进行轮训的操作去获取 master 的地址后再进行构建

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
