### ISSUE TITLE
Flink CDC 有支持 SAP-Hana 的计划吗

### ISSUE THREAD

**Issue by JanCong** [ververica/flink-cdc-connectors#1301]
Flink CDC 有支持 SAP-Hana 的计划吗

**Comment by Liugh2020** [comment]
+1

**Comment by Shoham-Yamin** [comment]
+1

**Comment by LegendOfGod** [comment]
+10086

**Comment by zqsgithub2023** [comment]
+1

**Comment by SinyoWong** [comment]
+1

**Comment by fly-shark** [comment]
+1

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
