### ISSUE TITLE
How to open Flink CDC's log in Flink Job?

### ISSUE THREAD

**Issue by JesseAtSZ** [ververica/flink-cdc-connectors#1308]
I am running my job in standlone mode, setting log level to debug in log4j.properties and log4j-cli.properties, works only on my Flink Job, but still can't found Flink CDC's log in Flink Job, What should I do in this situation？

I tried to set the level to ALL in log4j.properties, but there are too many logs.

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
