### ISSUE TITLE
Oracle CDC Whether the dynamic discovery of new tables is supported

### ISSUE THREAD

**Issue by Rowen110** [ververica/flink-cdc-connectors#1379]
Flink CDC Orcale Source Whether can support automatic scanning new table functions, like mysql CDC scanNewlyAddedTableEnabled feature function.

**Comment by hbk671104** [comment]
Need this so bad. +1

**Comment by e-mhui** [comment]
Oracle now supports automatically detecting newly added tables. What is the scenario of you?

**Comment by e-mhui** [comment]
@Rowen110 @hbk671104 pls review it https://github.com/ververica/flink-cdc-connectors/pull/2078 .

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
