### ISSUE TITLE
请问下CDC配置多个表是按表来获取binlog呢？还是按数据库实例来获取binlog呢？

### ISSUE THREAD

**Issue by bjddd192** [ververica/flink-cdc-connectors#147]
我们使用来CDC产品后，需要实时采集100多个表的数据(位于同一个数据库内)
发现会自动产生很多个SeverID，IO流量也很大，请问这个是否可以设置按数据库实例来获取binlog日志呢？每个表都去获取一份binlog日志有点浪费了吧？
还是我配置有问题，请指教，谢谢。

**Comment by wuchong** [comment]
@bjddd192 , 目前 flink cdc 只能每个表去拉取一份 binlog。 

你的需求是简单的数据同步吗（数据库数据实时同步到目标库）？同步过程中有 agg, join 等计算吗？

**Comment by fengfuli** [comment]
请问一下，在cdc 内部是给每个表都建一个topic吗？ 我看到日志中有这个 ConnectRecord{topic='mysql_binlog_source.test_db.tb1' ， 如果是的话，上千张表上千个topic 是否会影响性能？

**Comment by Assassinxc** [comment]
用datasteam的api可以实现一个库只拉取一份binlog

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
