### ISSUE TITLE
flink-connector-oracle-cdc

### ISSUE THREAD

**Issue by xpdgit123** [ververica/flink-cdc-connectors#1494]
flinkcdc 监听 Oracle：
flinkcdc 版本：2.2.1
Oracle 版本：Oracle Database 19c 

![image](https://user-images.githubusercontent.com/47846745/185859475-53b358cd-f4d1-45a7-aed8-9a910673521b.png)
使用时候报错：
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor

![image](https://user-images.githubusercontent.com/47846745/185859569-f3c6d823-e633-4fc0-a247-484944c2e691.png)

**Comment by chenfan331** [comment]
大佬，解决了吗？我也遇到了这个问题

**Comment by imrewang** [comment]
**My Solution**

schemaList":"XXX"

XXX is Service Name

**Comment by gong** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you! cc @GOODBOY008

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
