### ISSUE TITLE
请问一下大佬们，flink cdc 连接TiDB，支持获取 TiDB 的 DDL 吗？

### ISSUE THREAD

**Issue by MengXiangDing** [ververica/flink-cdc-connectors#1511]
请问一下大佬们，flink cdc 连接TiDB，支持获取 TiDB 的 DDL 吗？

**Comment by GOODBOY008** [comment]
Currently, don't support ddl.

**Comment by mxd-321** [comment]
thank you !

**Comment by mxd-321** [comment]
thank you !

**Comment by mxd-321** [comment]
thank you !

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
