### ISSUE TITLE
mysql-cdc并行度默认是1 请问是什么原因 修改整体并行度并不能更改其并行度 

### ISSUE THREAD

**Issue by kaohaonan6666** [ververica/flink-cdc-connectors#153]

**Comment by Tan-JiaLiang** [comment]
不能改，主要原因是你CDC同步，多线程并发处理，会导致数据混乱 
譬如：
第一条INSERT
第二条UPDATE
这两条数据都是关于一个主键的

然后Flink分布式并发处理的话
会变成
第一条UPDATE
第二条INSERT

这样会导致数据混乱

**Comment by zhisheng17** [comment]
source 可以只用 1 个并行度，sink 可以配置多个并行度（新版本已经有 kafka/hbase 支持设置 sink 并行度，也可以自己修改），中间根据主键进行 keyby

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
