### ISSUE TITLE
How to solve the problem of DML information loss

### ISSUE THREAD

**Issue by moonService** [ververica/flink-cdc-connectors#1535]
You can implement `debeziumdeserializationschema` to support your scenario

_Originally posted by @fuyun2024 in https://github.com/ververica/flink-cdc-connectors/issues/1256#issuecomment-1152504626_

same question，i wonder why update is split into create and delete？and which test case of the source code is used to test this？

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
