### ISSUE TITLE
tidb-cdc-connector 组件有考虑service GC safepoint吗

### ISSUE THREAD

**Issue by SoulSong** [ververica/flink-cdc-connectors#1593]
tidb-cdc-connector 组件有考虑service GC safepoint吗？如果不考虑，怎会在任务中断的情况下，由于tikv的gc导致数据丢失。

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
