### ISSUE TITLE
Any plan for Oracle 10g? and When support for Flink 1.5+

### ISSUE THREAD

**Issue by moly52** [ververica/flink-cdc-connectors#1596]
there is some db is oracle10g，and I want write data to oracle with flink-connector-jdbc.

**Comment by gong** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you! cc @GOODBOY008

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
