### ISSUE TITLE
有支持DDL的同步吗

### ISSUE THREAD

**Issue by walker-bichen** [ververica/flink-cdc-connectors#161]

**Comment by fengfuli** [comment]
Can CDC synchronize DDL ? I need schema and engine  from create table statement.

**Comment by wuchong** [comment]
@walker-bichen @fengfuli 能详细描述下你们的需求场景吗？ 比如:
- 从什么数据库，同步到，什么目的地？
- 希望同步什么样的 DDL 事件到目的地？
- 数据同步中涉及到 transformation 吗？ 比如过滤、清洗。

**Comment by walker-bichen** [comment]
希望flink能获取到源库中表结构字段的增，删，改操作，以及表创建和删除，至于目的数据库，可以是同构数据库，也可以是异构数据库，数据湖都行，这个在flink的sink进行逻辑处理，本身源端是关系数据库，我认为transformation可以弱化

**Comment by vrhappy** [comment]
如果增量同步过程中，源数据库又有新表建立，这时候增量同步应捕获到建表动作，并在目的库新建对应表，并继续执行同步。这样才能保证增量同步的完整性！

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
