### ISSUE TITLE
关于作业配置维护的问题

### ISSUE THREAD

**Issue by AlienFromStar** [ververica/flink-cdc-connectors#165]
由于CDC作业是长期性质的，若在使用中维护不佳，很可能会在排错过程及实际使用中造成影响，有几个问题想请教下：
1. 不同的作业建议使用不同的server_id，这对于mysql来说相当于挂载了多个可能是n个从库，会有很大的负载开销。
    若数据库表数量很多，初期数据同步作业，可能一个作业只有几个表，后续会过一段时间增加一部分表，每个作业的server_id都不一样，就会存在mysql同步多个从库的情况。
     可不可以对于某一个作业动态增加同步的表，减少server_id的增加？

2.mysql源会存在复杂的情况，比如主从切换（debezium支持修改源），主从同步失败，mysql主库需要reset master等等，这类复杂的源修改有没有准备方案？

3.作业状态是否可以通过api查出来，方便集成到已有的系统里？

谢谢！

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
