### ISSUE TITLE
[mysql] support read snapshot only 

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#1687]
we can support read snapshot only mode to unlock more user cases.

**Comment by PatrickRen** [comment]
Also we need to log the current offset once the binlog split reader reaches highest watermarks among snapshot splits (pure binlog reading mode)

**Comment by SML0127** [comment]
I also need this feature..

**Comment by waitingF** [comment]
hihihi, any news?

**Comment by leonardBang** [comment]
@PatrickRen Could you kindly look at this request ?

**Comment by punish-yh** [comment]
I am very looking forward to this new feature

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
