### ISSUE TITLE
cdc 有没有返回一个时间字段,这个字段指的是这条数据CRUD的时间,这样我就可以这个时间来做watermark

### ISSUE THREAD

**Issue by tb77506668** [ververica/flink-cdc-connectors#195]
cdc 有没有返回一个时间字段,这个字段指的是这条数据CRUD的时间,这样我就可以这个时间来做watermark

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
