### ISSUE TITLE
mysql 数据库切换导致cdc 消费binlog出错，是否支持gtid同步？

### ISSUE THREAD

**Issue by gitdongjian** [ververica/flink-cdc-connectors#200]
dba进行数据库备库切换操作，导致binlog出错
dba反馈数据库已经支持gtid的同步方式，目前cdc这边好像还不支持？
org.apache.kafka.connect.errors.ConnectException: The connector is trying to read binlog starting at GTIDs 3fa7d5bb-65f3-11eb-9413-b0262879b560:1-730774004 and binlog file 'mysql-bin.000650', pos=521310219, skipping 2 events plus 1 rows, but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
