### ISSUE TITLE
flink-cdc 如何支持分库场景下的MySQL

### ISSUE THREAD

**Issue by Su1024** [ververica/flink-cdc-connectors#201]
背景，我司的MySQL都是分库的，那么在配置FLINK CDC的时候 是一个库一个CDC任务吗？还是说已经可以支持到分库的MySQL CDC任务了

**Comment by 812406210** [comment]
![image](https://user-images.githubusercontent.com/22192011/120612551-e49c2700-c487-11eb-9d91-ce3a458d8a1a.png)
只支持表正则

**Comment by 812406210** [comment]
![image](https://user-images.githubusercontent.com/22192011/120612732-13b29880-c488-11eb-8799-7477099449af.png)
大佬可以试试，到时候可以说下结果以及大概的配置

**Comment by Su1024** [comment]
如果是分库的话，我们链接的url应该是一个库一个 url 这种应该更加适合分表 使用正则来匹配处理 不满足我们的需求

**Comment by 812406210** [comment]
> 如果是分库的话，我们链接的url应该是一个库一个 url 这种应该更加适合分表 使用正则来匹配处理 不满足我们的需求

实在不行，就都发kafka同一个topic，然后再flinksql 消费写入

**Comment by dongdongking008** [comment]
你这是多实例吧，可以起多个source然后union到一起。当然，每个source你自己做发现，毕竟都是多个实例了，没法去自动发现实例

**Comment by Su1024** [comment]
> ，

如果是这样的哈，那我觉得flink 还不如把数据库的binlog订阅到kafka来消费了

**Comment by imkew** [comment]
现在我司暂时搞的是一个库一个cdc任务，暂时没找到好的解决方案，蹲一个。

**Comment by imkew** [comment]
@leonardBang 这块目前有什么最佳实践吗

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
