### ISSUE TITLE
读取mysql默认字符集是utf-8吗，如果数据源是gbk的，有选项可以解码吗

### ISSUE THREAD

**Issue by naive1992** [ververica/flink-cdc-connectors#218]

**Comment by leonardBang** [comment]
暂时没有

**Comment by naive1992** [comment]
我修改debezium源码连接实现了，我们数据库是gbk字符集编码

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
