### ISSUE TITLE
mysql-cdc采用DataStream Api方式 如何获取DDL语句呢？

### ISSUE THREAD

**Issue by jazzyMin** [ververica/flink-cdc-connectors#236]
flink DataStream API how to get ddl ？

**Comment by fsk119** [comment]
获取 ddl 是为了什么呢？

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
