### ISSUE TITLE
[Bug] mongo 连接密码中有特殊字符的情况验证错误

### ISSUE THREAD

**Issue by xqyphp** [ververica/flink-cdc-connectors#2365]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17

### Flink CDC version

2.4.1

### Database and its version

mongodb6.0

### Minimal reproduce step

连接传入带#号的密码或用户名

### What did you expect to see?

正常连接

### What did you see instead?

验证失败

### Anything else?

com.ververica.cdc.connectors.mongodb.internal.MongoDBEnvelope.encodeValue方法中转换成URL有误#号不需要转换

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by xqyphp** [comment]
官方文档中: / ? # [ ] @都需要编码，但是我测试的时候#编码确连接不成功，不知道到底是mongodb的BUG还是这个库的BUG

**Comment by yuxiqian** [comment]
Seems weird since there are [test cases](https://github.com/ververica/flink-cdc-connectors/blob/823f5a1e21009e2e0ba36cd44ec15353e3cbcd67/flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/utils/MongoDBContainer.java#L55) covering special characters in password.

CDC 2.4.1 relies with MongoDB driver 4.3.4, which is said to be [incompatible](https://www.mongodb.com/docs/drivers/java/sync/current/compatibility/) with MongoDB 6.0.  Maybe you can try building a 2.5-snapshot from `master` branch?
