### ISSUE TITLE
[Mysql] RowDataDebeziumDeserializeSchema这个类有没有计划自动获取mysql table的schema呢

### ISSUE THREAD

**Issue by zhougit86** [ververica/flink-cdc-connectors#242]
RowDataDebeziumDeserializeSchema这个类有没有计划自动获取mysql table的schema呢

**Comment by leonardBang** [comment]
获取schema简单，关键问题获取之后框架如何处理schema信息，目前框架只处理的data信息

**Comment by zhougit86** [comment]
> 获取schema简单，关键问题获取之后框架如何处理schema信息，目前框架只处理的data信息

这边感觉可以通过jdbc获取到ddl之后用calcite解析成flink的datatype自动生成schema，可以节省自己做ddl->rowtype转换的过程

**Comment by fsk119** [comment]
> > 获取schema简单，关键问题获取之后框架如何处理schema信息，目前框架只处理的data信息
> 
> 这边感觉可以通过jdbc获取到ddl之后用calcite解析成flink的datatype自动生成schema，可以节省自己做ddl->rowtype转换的过程

是说直接使用通过表名直接获取 schema，用户不需要手动写繁琐的ddl吗？

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
