### ISSUE TITLE
flink cdc 写入mysql速度很慢，有什么优化的方式吗？

### ISSUE THREAD

**Issue by ghost** [ververica/flink-cdc-connectors#272]
您好，就是我在使用flink cdc 的时候，数据写入到下游mysql的时候一个小时只能写几十万条，这个有优化方式吗，我看了没有产生背压。2就是我看flink cdc实际上是将debezium 和kafka封装起来了，但是我在看同步日志的时候，每次拉取10000条，写入下游后再继续拉取下一批。不是source一直拉取数据到kafka，然后下游在消费kafka数据这种解耦的设计吗？

**Comment by yaoboxu** [comment]
flink 写入mysql 采用的方式是类似这种：INSERT INTO table (a,b,c) VALUES (1,2,3) ON DUPLICATE KEY UPDATE c=c+1
我们一个大宽表，类似有10多个表进行join，一天下来日志300G+的binlog日志，如果你们开启了binlog。

后续我的思路 是换用tidb或者clickhouse作为结果库，mysql写入的这个日志已经把我烦死了。

**Comment by xiaoshijiang523** [comment]
> flink 写入mysql 采用的方式是类似这种：INSERT INTO table (a,b,c) VALUES (1,2,3) ON DUPLICATE KEY UPDATE c=c+1
> 我们一个大宽表，类似有10多个表进行join，一天下来日志300G+的binlog日志，如果你们开启了binlog。
> 
> 后续我的思路 是换用tidb或者clickhouse作为结果库，mysql写入的这个日志已经把我烦死了。

你如果是用tidb的话，他有专门的工具来做这个，可配置的，没必要用flink cdc，我现在写入mysql用的自定义的jdbc sink 速度太慢，因为一个数据源多个库，表数据量大，一小时才几十万同步。

**Comment by NoTwo-wyd** [comment]
我写入mysql表的jdbc加入了rewriteBatchedStatements=true，效果还不错，不加这个jdbc参数性能很差

**Comment by miaogr86** [comment]
&rewriteBatchedStatements=true 数据库连接加上这个参数试试

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
