### ISSUE TITLE
MySQL timestamp type convert to user-define timezone

### ISSUE THREAD

**Issue by NextMark** [ververica/flink-cdc-connectors#28]
When sync data from mysql binlog, timestamp column alway be converted to UTC timezone, we need implements debezium CustomConverter class to convert to our timezone.

**Comment by wuchong** [comment]
Did you try to use the [server-time-zone](https://github.com/ververica/flink-cdc-connectors/wiki/MySQL-CDC-Connector#server-time-zone) option?

**Comment by NextMark** [comment]
> Did you try to use the [server-time-zone](https://github.com/ververica/flink-cdc-connectors/wiki/MySQL-CDC-Connector#server-time-zone) option?

It has been set to “Asia/Shanghai” and still does not take effect，and the timestamp field I got is 8 hours less than in the database.

**Comment by ledonglin** [comment]
I also encountered with this issue. I add the timezone after the url and it works.
 Hope this can help you.

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
