### ISSUE TITLE
StartupMode为EARLIEST_OFFSET或TIMESTAMP时不能正常解析

### ISSUE THREAD

**Issue by ashulin** [ververica/flink-cdc-connectors#298]
flink-cdc版本：master
现象：当使用StartupMode为EARLIEST_OFFSET或TIMESTAMP时，即debezium的snapshot.mode = never时，不能获取到binlog的数据；

原因：debezium mysql在1.5+对接口进行了重构，修改了很多代码，debezium-mysql对io.debezium.connector.mysql.MySqlConnectorConfig.SnapshotMode中添加了很多配置：
```java
   public static enum SnapshotMode implements EnumeratedValue {

        /**
         * Perform a snapshot when it is needed.
         */
        WHEN_NEEDED("when_needed", true, true, true, false, true),

        /**
         * Perform a snapshot only upon initial startup of a connector.
         */
        INITIAL("initial", true, true, true, false, false),

        /**
         * Perform a snapshot of only the database schemas (without data) and then begin reading the binlog.
         * This should be used with care, but it is very useful when the change event consumers need only the changes
         * from the point in time the snapshot is made (and doesn't care about any state or changes prior to this point).
         */
        SCHEMA_ONLY("schema_only", true, false, true, false, false),

        /**
         * Perform a snapshot of only the database schemas (without data) and then begin reading the binlog at the current binlog position.
         * This can be used for recovery only if the connector has existing offsets and the database.history.kafka.topic does not exist (deleted).
         * This recovery option should be used with care as it assumes there have been no schema changes since the connector last stopped,
         * otherwise some events during the gap may be processed with an incorrect schema and corrupted.
         */
        SCHEMA_ONLY_RECOVERY("schema_only_recovery", true, false, true, true, false),

        /**
         * Never perform a snapshot and only read the binlog. This assumes the binlog contains all the history of those
         * databases and tables that will be captured.
         */
        NEVER("never", false, false, true, false, false),

        /**
         * Perform a snapshot and then stop before attempting to read the binlog.
         */
        INITIAL_ONLY("initial_only", true, true, false, false, false);

        private final String value;
        private final boolean includeData;
        /**
         * 以下为新增属性.
         */
        private final boolean includeSchema;
        private final boolean shouldStream;
        private final boolean shouldSnapshotOnSchemaError;
        private final boolean shouldSnapshotOnDataError;
}
```
never时includeSchema属性为false，其会导致debeizum不读取table schema，而在1.4中并没有相关的判断，由于没有读取schema，实际不能解析log event。从而导致EARLIEST_OFFSET或TIMESTAMP不可用。

**Comment by hzh2955** [comment]
我这边也遇到了这个问题。   use StartupOptions.earliest() model get binlog error #289

**Comment by leonardBang** [comment]
StartupMode的 EARLIEST_OFFSET， SPECIFIC-OFFSET  和 TIMESTAMP选项的现有实现都有问题，原因如果遇到schema已经变化了或者binlog被清理掉了，我已经准备暂时禁用这三个选项，直到我们正确地支持它们。

**Comment by hzh2955** [comment]
可以加个钉钉交流下不？&nbsp; 讨论下看看怎么解决，这边一定帮忙开发。&nbsp; &nbsp;+86-18986081520 贺正红



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Leonard ***@***.***&gt;; 
发送时间: 2021年8月11日(星期三) 上午10:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ververica/flink-cdc-connectors] StartupMode为EARLIEST_OFFSET或TIMESTAMP时不能正常解析 (#298)





 
StartupMode的 EARLIEST_OFFSET， SPECIFIC-OFFSET  和 TIMESTAMP选项的现有实现都有问题，原因如果遇到schema已经变化了或者binlog被清理掉了，我已经准备暂时禁用这三个选项，直到我们正确地支持它们。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ili-zh** [comment]
> StartupMode的 EARLIEST_OFFSET， SPECIFIC-OFFSET 和 TIMESTAMP选项的现有实现都有问题，原因如果遇到schema已经变化了或者binlog被清理掉了，我已经准备暂时禁用这三个选项，直到我们正确地支持它们。

我测试了SPECIFIC-OFFSET模式，是可以正常使用的。当然指定的offset时的表结构需要和当前一致，由于Flink CDC -> Sink实际是不支持DDL同步的，我觉得SPECIFIC-OFFSET模式以目前来看是正常的。

**Comment by leonardBang** [comment]
Flink CDC 有钉钉群的，大家可以加群后讨论
![image](https://user-images.githubusercontent.com/5163645/128967519-59386530-d9a3-4a0f-b05b-903f08042891.png)

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
