### ISSUE TITLE
There may be some problems with the function description of `server-id`.

### ISSUE THREAD

**Issue by carryxyh** [ververica/flink-cdc-connectors#306]
![image](https://user-images.githubusercontent.com/12047600/129133825-678fa115-6eb8-4232-aeee-7a7442cae32f.png)

In the description of server-id, it is written that server-id will be used to maintain the binlog pos of mysql.

Regarding this point, in the master-slave replication, mysql maintains its own position by the slave, and the server-id is only used as a unique identifier for the slave. And in debezium, I did not find information about server-id used to maintain binlog pos in the document.

Is this an error in the description? Please let me know if I am wrong.

**Comment by leonardBang** [comment]
@carryxyh I think the document is ok because `MySqlSouce`  keep the binlog position in `state` for each checkpoint, the `manage` means managing the state and failover using the `state`.

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
