### ISSUE TITLE
[SUPPORT]How checkpoint is implemented when cdc the full data in 2.0

### ISSUE THREAD

**Issue by bithw1** [ververica/flink-cdc-connectors#309]
It is said that flink mysql cdc 2.0 supports checkpointing for exactly once gurantee during the phrase of cdc full data.

I know flink supports WAL and 2PC checkpointing mechanism for exactly once gurantee ,I would ask how checkpoint is implemented in this scenario.

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
