### ISSUE TITLE
[docs] Add contribution guidance section in document

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#345]
We need add contribution guidance section in document, e.g. develop environment setting, code format, PR description
We can add it in `readme.md` and `about.md`

**Comment by MonsterChenzhuo** [comment]
Hi @leonardBang I am very interested in this，and I want do some job for flink-cdc，can I help to do that？
Thank you

**Comment by leonardBang** [comment]
Thanks @MonsterChenzhuo for taking this,  I've assigned to you.

**Comment by leonardBang** [comment]
@MonsterChenzhuo  you can refer https://github.com/ververica/flink-cdc-connectors/issues/340 when you write the documentation

**Comment by gtk96** [comment]
@ruanhang1993 @GOODBOY008 @Jiabao-Sun I'm interested in it.

**Comment by GOODBOY008** [comment]
@gtk96 Assigned

**Comment by saadaqnuur** [comment]
Hi everyone! I'm new to the project and excited about the opportunity to contribute. This issue caught my eye as a great way to get started. I'd appreciate any guidance on how to approach this. Are there any specific resources or documentation I should refer to? Thanks for your help!

**Comment by gtk96** [comment]
> Hi everyone! I'm new to the project and excited about the opportunity to contribute. This issue caught my eye as a great way to get started. I'd appreciate any guidance on how to approach this. Are there any specific resources or documentation I should refer to? Thanks for your help!

I'm glad that you are willing to contribute to this.
I have submitted the pr of this question. Can you help me review it?

**Comment by saadaqnuur** [comment]
Yes @gtk96! Thank you for taking the initiative to address this issue by submitting the pull request. I'd be happy to help review it and provide feedback.

I'm new to the project and eager to contribute. This issue seems like a great way to start, and I'm particularly interested in adding the contribution guidance section to the document. Could you please provide some guidance on how to approach this? Are there any specific resources or documentation I should refer to in order to make a meaningful contribution?

Looking forward to your advice. Thanks in advance!

@saadaqnuur
