### ISSUE TITLE
使用flinkcdc stream模式时，增量读取binlog阶段，insert操作时出现主键冲突。

### ISSUE THREAD

**Issue by ghost** [ververica/flink-cdc-connectors#363]
使用flinkcdc stream模式时，初始化之前先将表数据truncate ，然后启动程序初始化，然后拉取增量binlog，程序是按用户操作类型分流的，结果在insert操作时出现Duplicate entry '' for key 'PRIMARY'这个报错，主键冲突，这可能是什么原因呢

**Comment by luxuebao** [comment]
我测试也是这样的，在 'scan.incremental.snapshot.enabled'='true',的配置下，snapshot读完了之后，+I的数据，会再次+I一次，应该是binlog又重复读取了已经插入的数据

**Comment by luxuebao** [comment]
@xiaoshijiang523 请问问题解决了吗

**Comment by leesenlen** [comment]
#1414  类似这个问题

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
