### ISSUE TITLE
flink 启动的时候没有数据

### ISSUE THREAD

**Issue by vissul** [ververica/flink-cdc-connectors#5]
麻烦问下  flink 启动的时候没有数据 是怎么回事？

**Comment by wuchong** [comment]
请问你是跟着教程一步步走下来的吗？是用的自己的 mysql，还是 demo 里的 mysql 容器？重启 flink 集群试过了么？

**Comment by vissul** [comment]
都是按照您b站的视频 启动的 flink任务也没报错 启动的都是docker里面的mysql 和 pg 啥也没改  es里面就是没数据

**Comment by jeffreyWaaaaaaa** [comment]
> 都是按照您b站的视频 启动的 flink任务也没报错 启动的都是docker里面的mysql 和 pg 啥也没改 es里面就是没数据
你数据库里有数据吗？依赖包有导入到flink/lib下吗？

**Comment by wuchong** [comment]
0. 进入 mysql ，看看表中有没有数据
1. 观察 Flink Web UI 上的拓扑图上， 最后一个节点的 received records 的 metric 有没有值
2. 如果没有 received records， 重启 flink cluster 再试一试。

**Comment by kimmazhenxin** [comment]
> 都是按照您b站的视频 启动的 flink任务也没报错 启动的都是docker里面的mysql 和 pg 啥也没改 es里面就是没数据

楼主这个B站视频怎么能看到？

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
