### ISSUE TITLE
read snapshot from ReadOnlyInstance and read binlog from master

### ISSUE THREAD

**Issue by undefang** [ververica/flink-cdc-connectors#511]
To reduce impact on master, sometimes I expect cdc to read snapshot from ReadOnlyInstance. Beside, aliyun rds:ReadOnlyInstance has no binlog，I must read binlog from master.
So, can cdc support read snapshot from ReadOnlyInstance and read binlog from master(support configure master&ReadOnlyInstance address)?

**Comment by wuchong** [comment]
Thanks @undefang , I think this is a nice feature. Besides you said "aliyun rds slave has no binlog", is there any documentation explain it?

**Comment by undefang** [comment]
> Thanks @undefang , I think this is a nice feature. Besides you said "aliyun rds slave has no binlog", is there any documentation explain it?

Sorry，I made a mistake. It‘s ReadOnlyRDSInstance that i can not read the binlog.

**Comment by wuchong** [comment]
Thanks @undefang , is there any docs for that as well?

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
