### ISSUE TITLE
mysql 传错误的hostname和username，会返回Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by lea21st** [ververica/flink-cdc-connectors#545]
mysql 传错误的hostname和username，会返回Public Key Retrieval is not allowed，应返回正确的错误信息。

**Comment by paul8263** [comment]
Hi @lea21st ，
According to mysql-cdc doc, it seems that your password type is sha256_password.

Explanation is as below:
This is because the MySQL user account uses `sha256_password` authentication which requires transporting password under protection like TLS protocol. A simple way is to enable the MySQL user account use naive password.
```sql
-- MySQL
ALTER USER 'username'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
FLUSH PRIVILEGES;
```

**Comment by lea21st** [comment]
yeah
