### ISSUE TITLE
一个任务不同时间添加表，如何让后面添加的表从头开始读取数据，之前添加的表按当前时间读取？

### ISSUE THREAD

**Issue by zanmeipaul** [ververica/flink-cdc-connectors#55]
flink 通过api 的方式同步数据:

需求如下:
1. 第一次同步添加 A表
```
MySQLSource.<String>builder().tableList("A")
```

2. 然后把 flink 任务停了，添加一张B表

```
MySQLSource.<String>builder().tableList("A,B")
```

3. flink 启动 run 添加上 -s checkpoints， 
   让 A表从上一次状态开始同步，B 表从头开始同步

目前的现状是:   A表可以从上次开始同步，可是B表数据发送变化会把A表和B表全部数据都同步一遍

**Comment by shizhengchao** [comment]
这的确是一个问题，在这篇文章中提到了 https://www.jianshu.com/p/66adedf25ee9?utm_campaign=haruki ，目前这个项目使用的debezium不是最新的。
这个应该是debezium再加的功能，不确定最新版本有没有实现：
修改同步任务的table.whitelist后，debezium可以自动完成新增表的全量和增量同步，并且这个过程不会干扰原有的同步任务；当新老两批同步任务进度相近时，合二为一，只使用同一个BinlogReader完成后续的stream同步。

这个可能是一个优化点。 @wuchong

**Comment by zanmeipaul** [comment]
@shizhengchao    谢谢你的回答，我今天试了debezium 1.3.0 版本，确实有这个功能。 目前文档上没有开放出来，默认是关闭的，我设置了 snapshot.new.tables 为 parallel 后生效。 目前不知这个功能是否稳定

**Comment by wuchong** [comment]
我们会在近期升级 debezium 依赖。

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
