### ISSUE TITLE
flink CDC should add monitoring to Flink's own accumulator

### ISSUE THREAD

**Issue by yuangjiang** [ververica/flink-cdc-connectors#587]
Flink CDC should add monitoring to Flink's own accumulator:
For example, the total 
1.number of records to be queried, 
2.the time when the data was changed, 
3.the current query location, 
4.the parsing of error records ,
5.the number of warnings detected.

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
