### ISSUE TITLE
基于ogg的采集，未来有规划么？大概多久才能推出

### ISSUE THREAD

**Issue by qyw919867774** [ververica/flink-cdc-connectors#74]

**Comment by snycc15** [comment]
同问

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
