### ISSUE TITLE
2.x CDC can't not support "double write"

### ISSUE THREAD

**Issue by yaoboxu** [ververica/flink-cdc-connectors#741]
**Describe the bug**
2.x CDC can't not support "double write".  When i create a view consists of some tables joins, i want write the result into different databases,
After i write to one database,  i can't query this view in flink sql client because of server_id. The error reports the server_id is  duplicate.

**Environment :**
 - Flink version :  flink1.13.3
 - Flink CDC version: 2.02 or 2.1.1

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
