### ISSUE TITLE
When can  CDC support  for speical table read  snapshot  and latest only 

### ISSUE THREAD

**Issue by dutao1** [ververica/flink-cdc-connectors#786]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by dutao1** [comment]
When can support  for speical table read  snapshot  and latest only 。


Chinese: 什么时候可以支持 指定部分表做全量+增量，部分表做增量，部分表只做全量？

因为有很多场景 需要重刷数据；但是只刷部分表数据，其他表需要正常拉取。
辛苦解答！

**Comment by YesOrNo828** [comment]
> 

#513  应该与这个issue相关，社区正在做了，已经提了相关[pr](https://github.com/ververica/flink-cdc-connectors/pull/777)

**Comment by dutao1** [comment]
> 

Thanks!

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
