### ISSUE TITLE
ddl support

### ISSUE THREAD

**Issue by sunfu103** [ververica/flink-cdc-connectors#795]
什么时候支持ddl？
上游数据源schema修改
flink-cdc可以自动修复下游动态表schema

**Comment by zhjwpku** [comment]
这个如果使用 Stream API 的话是已经支持了的，`includeSchemaChanges` 置为 true 可以保证数据流中包含 DDL，可以在 stream job 中进行相应处理。

**Comment by rookiegao** [comment]
SQL 方式自动同步 schema 由云邪老师带领的团队开发过了，但尚未开源，目前只能自己通过Stream API 来解决。

**Comment by eastfisher** [comment]
> SQL 方式自动同步 schema 由云邪老师带领的团队开发过了，但尚未开源，目前只能自己通过Stream API 来解决。

是指阿里云Flink的CDAS和CTAS吗？可以支持gh-ost相关DDL，以及下游为MySQL / TiDB么？

**Comment by jinghewang** [comment]
这个功能很重要，现在主流的数据湖工具都已经支持了，希望可以开源，尽快加入。

**Comment by zfanswer** [comment]
+1

**Comment by caijiljh** [comment]
+1

**Comment by yuandajn578** [comment]
+1

**Comment by tianhao960** [comment]
+1

**Comment by JageChen** [comment]
+1

**Comment by giangnth** [comment]
+1

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
