### ISSUE TITLE
[mysql] Use Incremental Snapshot Framework for MySql CDC Connector

### ISSUE THREAD

**Issue by zhjwpku** [ververica/flink-cdc-connectors#851]
**Is your feature request related to a problem? Please describe.**

Adapte MySql CDC Connector to the abstraction framework of #724 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by zhjwpku** [comment]
Hi @leonardBang, please assign me to this issue, I'll help to adapt the MySql CDC Connector to the Incremental Snapshot Framework.

**Comment by leonardBang** [comment]
Thanks for picking up this ticket, assigned this ticket to you @zhjwpku

**Comment by Peng-89** [comment]
> Thanks for picking up this ticket, assigned this ticket to you @zhjwpku
Is this problem solved now?

**Comment by Peng-89** [comment]
Is this problem solved now?

**Comment by leonardBang** [comment]
Resolved in #1079

**Comment by ruanhang1993** [comment]
@zhjwpku Is there any progress about this issue? Thanks~

**Comment by zhjwpku** [comment]
> @zhjwpku Is there any progress about this issue? Thanks~

sorry, haven't got time with this issue recently, you can take over this if you like :)

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
