### ISSUE TITLE
use bot to simplify patch to release branch operations

### ISSUE THREAD

**Issue by teckick** [ververica/flink-cdc-connectors#859]
**Is your feature request related to a problem? Please describe.**

flink-cdc has several release git branches, such as release-2.1, release-2.0. When merging a new PR into master, we have to repeat the PR into these release branches using git cherry-pick command. This operation can be automatically done by bot like [cherry-bot](https://github.com/tidb-incubator/cherry-bot).

**Describe the solution you'd like**

Add a bot to do cherry-pick operations to release branches.

**Describe alternatives you've considered**

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
