### ISSUE TITLE
Can we have a blog module in flink-cdc-connectors website?

### ISSUE THREAD

**Issue by GOODBOY008** [ververica/flink-cdc-connectors#970]
Can we have a blog module on flink-cdc-connectors website? We can choose some articals and best practices for beginners to start up quickly. @wuchong @leonardBang  What do you think about this idea?

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
