### ISSUE TITLE
[task] Add metric supports for tidb-cdc connector

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#974]
We introduce TiDB CDC Connector in #243 , we can support metrics for this connector

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
